name: aipg_xpu_ultra
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - opencv
  - pillow=10.3.0
  - psutil=5.9.8
  - requests=2.32.3
  - scikit-image
  - scipy
  - pandas
  - flask=3.0.3
  - click
  - jinja2
  - itsdangerous
  - werkzeug
  - setuptools=69.5.1
  - pydantic
  - python-dotenv
  - libjpeg-turbo
  - libpng
  - pip:
      - basicsr==1.4.2
      - compel==2.0.2
      - datasets==2.18.0
      - diffusers==0.27.2
      - huggingface_hub==0.22.2
      - ipex_llm==2.1.0b20240705
      - langchain>=0.2.9,<0.3.0
      - langchain_community==0.2.9
      - langchain_core>=0.2.22,<0.3.0
      - peft==0.10.0
      - sentence_transformers==2.3.1
      - transformers==4.39.0
      - trl==0.9.3
      - bigdl-core-xe-21==2.5.0b20240705
      - bigdl-core-xe-addons-21==2.5.0b20240705
      - bigdl-core-xe-batch-21==2.5.0b20240705
      - faiss-cpu==1.8.0
      - docx2txt==0.8
      - pypdf==4.2.0
      - unstructured==0.14.6
