[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
strict_optional = True
exclude = build/|dist/|node_modules/|\.git/|\.venv/|venv/|env/|\.github/workflows/scripts/

[mypy.plugins.numpy.*]
follow_imports = skip

[mypy.plugins.torch.*]
follow_imports = skip

[mypy-service.*]
ignore_missing_imports = True

[mypy-intel_extension_for_pytorch]
ignore_missing_imports = True

[mypy-rag]
ignore_missing_imports = True 