[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
exclude = build/|dist/|node_modules/|\.git/|\.venv/|venv/|env/

[mypy.plugins.numpy.*]
follow_imports = skip

[mypy-torch.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True 