#!/bin/bash
# Compatibility Report Generator
# This script creates a report documenting compatibility with different Python versions and environments

echo "Generating compatibility report..."

# Create the report directory
mkdir -p compatibility_report

# Get the Python version from matrix
PYTHON_VERSION=${1:-"unknown"}

# Generate the report
cat > compatibility_report/README.md << EOF
# Compatibility Report

This report is automatically generated by the CI workflow to document compatibility with different Python versions and environments.

## Matrix Test Information

| Python Version | Status | Details |
|----------------|--------|---------|
| Python $PYTHON_VERSION | ✅ Current Run | [View Details](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) |

## Platform Support

| Platform | Status | Notes |
|----------|--------|-------|
| CPU (x86) | ✅ Supported | Primary development target |
| Intel GPU (XPU) | ✅ Supported with patches | Requires Intel Extension for PyTorch |
| NVIDIA GPU (CUDA) | ⚠️ Limited Support | Not tested in CI |
| Apple Silicon | ⚠️ Limited Support | Not tested in CI |

Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

*This is an automated report generated from workflow run #$GITHUB_RUN_NUMBER*
EOF

echo "Compatibility report generated for Python $PYTHON_VERSION" 