name: Ruff
on:
  push:
    paths:
      - "service/**/*.py"
      - ".github/workflows/ruff.yml"
  pull_request:
    paths:
      - "service/**/*.py"
      - ".github/workflows/ruff.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v1
        with:
          src: "./service"
          args: --ignore=F401,W291,F821,N801,N802,N803 --exit-zero --output-format=github
          changed-files: "true"

      # Add a step to notify about linting status
      - name: Linting Status
        run: |
          echo "Note: Ruff linting is currently set to always pass while we address technical debt."
          echo "Ruff linting results are provided for information only."
